name: Build (Development)

on:
  push:
    tags: ["dev-*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-reusable.yml
    with:
      profile: development
      branch: develop
      extension: apk
      prerelease: true
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
